//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yuro4ka
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductOrderSV
    {
        public int id { get; set; }
        public Nullable<int> productid { get; set; }
        public Nullable<int> orderid { get; set; }
    
        public virtual OrderList OrderList { get; set; }
        public virtual Product Product { get; set; }
    }
}
