//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yuro4ka
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductOrders___
    {
        public int Id { get; set; }
        public Nullable<int> Number { get; set; }
        public string Name { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<decimal> Total { get; set; }
    }
}
