//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yuro4ka
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserService
    {
        public int id { get; set; }
        public int Userid { get; set; }
        public int Serviceid { get; set; }
    
        public virtual Service Service { get; set; }
        public virtual User User { get; set; }
    }
}
