//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yuro4ka
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDocument
    {
        public int Id { get; set; }
        public int Documentid { get; set; }
        public int Bakerid { get; set; }
    
        public virtual Document Document { get; set; }
        public virtual User User { get; set; }
    }
}
